### ISSUE TITLE
There is no License file on the project

### ISSUE THREAD

**Issue by rlam1** [baylej/tmx#12]
While technically this repo accepts the Github [Terms](https://github.com/site/terms), we are only allowed to fork the program inside Github, but a third-party is now allowed to legally edit this code or even use it for personal or commercial purposes.

 I recommend you to always add a License to your projects so that one can know what can be done and what cannot. Take a look [here](http://choosealicense.com/) if you need help with that.

Hint: I would personally appreciate that you accept any license there, but not the GPL or LGPL... I dont like them that much...

**Comment by rlam1** [comment]
OK so I wrote that while I was struggling with compiling my own libxml2 and zlib binaries and did not happen to see that there was a file named COPYING.... how silly of me... Pretend this two posts never happened please... *puts head inside the ground*

**Comment by baylej** [comment]
Hi @rlam1,

There is binary distributions of libxml2 for windows/linux/macOS here: http://xmlsoft.org/downloads.html

Same for Zlib: http://zlib.net/ (Related External Links section)

**Comment by rlam1** [comment]
Yes, thanks for providing those, the library fully works on windows' vs2013. Wanted to go the hard way compiling the dependencies just for the experience, didn't work as expected heh... now on to build something nice with it! Thanks!
