### ISSUE TITLE
Parsing error when reading point values in <polygon> and <polyline>

### ISSUE THREAD

**Issue by rlam1** [baylej/tmx#13]
Suppose we have a xml(*.tmx) encoded map that contains a `<objectgroup>` layer, in this layer, we have the following object:

    <object id="19" x="260" y="293.333">
       <polygon points="0,0 224,141.333 -12,262.667 -224,180 -201.333,42.6667"/>
    </object>

When tmx is reading this file, it fails reading and storing the points in a `tmx_object->points` array. Instead, it throws an error **`xml parser: corrupted point list`**, in a JSON file, it throws **`json parser: (tileset) Expected integer, got real`**.

Upon inspection of `tmx_xml.c` I found the issue resides on line 131: The parser is expecting an integer value, *and can only store an integer value*, but *QtTiled* stores the coordinates as floating point values. This causes `sscanf` to fail and the entire parser bails out, not loading the map.

A **workaround** exists, after saving the map on the editor, manually open it on notepad or other text editor and delete the decimal point and the values after it in each coordinate pair, so the object will now read:

    <object id="19" x="260" y="293.333">
       <polygon points="0,0 224,141 -12,262 -224,180 -201,42"/>
    </object>

It will not be pixel-perfect this way, but at least the parser will not complain :stuck_out_tongue_winking_eye:. This is the method the examples currently use to overcome this limitation.

**Comment by rlam1** [comment]
First I thought it was a trivial change from `int`to `double` or `float` on all sections that produced this error, and was developing a pull request for the fix... But it ended being harder than my capacity.

**Comment by baylej** [comment]
Hi @rlam1,

I misunderstood [the reference](http://doc.mapeditor.org/reference/tmx-map-format/#object) ... it reads that coordinates are 'in pixels', so I assumed they were integers, not reals.

That's not easy to fix, there is a lot of code to change!

**Comment by baylej** [comment]
QtTiled uses the `qreal` type which is a typedef for double.
See https://github.com/bjorn/tiled/blob/master/src/libtiled/mapobject.h
