### ISSUE TITLE
tile objectgroups/objects missing

### ISSUE THREAD

**Issue by HowPrice** [baylej/tmx#15]
The Tiled Collision Editor can be used to add objects to a tile in a tileset. e.g.

```
 <tileset firstgid="1" name="..\Data\level1-Tileset" tilewidth="8" tileheight="8" tilecount="621">
  <image source="level1-Tileset.png" width="216" height="184"/>
  <tile id="4">
   <objectgroup draworder="index">
    <object id="0" x="3" y="8">
     <polyline points="0,0 5,-6"/>
    </object>
   </objectgroup>
  </tile>
 </tileset>
```

It looks like the data is not parsed by the library and the tmx_tile data structure does not support objects. I need this for my project so I'll can try to implement, unless I've overlooked WIP or another issue perhaps?

**Comment by baylej** [comment]
Hi,

This is already done in my [WIP branch](https://github.com/baylej/tmx/tree/wip), see commit no. 7f44296e56.
I still have to merge this branch.

You can `git checkout` that branch to get the code. please comment here if you fond a bug in the tile collision code.

Thanks.

**Comment by baylej** [comment]
Hi,
Commit 7f44296e56 is now merged into master branch.
