### ISSUE TITLE
Tiles need to keep track of animations internally.

### ISSUE THREAD

**Issue by reworks** [baylej/tmx#17]
Maybe a unsigned integer to keep track of the current animation, relative to each tile. It would be incremented each update, and checked against ``` animation_len ``` to prevent it going out of bounds (this would be done by the user).

```c
_tmx_tile {
    unsigned int current_animation;
}

```

**Comment by baylej** [comment]
Hi @reworks,

I might be overthinking this issue a little, here are my thoughts:

I think a `void *userdata` would better suit everyone's needs.
And if you only need an int, you can use this field as an int with the cast operator.
A union would be more explicit, but it must also contain a float (once again to suit everyone's needs).
```c
union {
	int integer;
	float decimal;
	void *pointer;
} userdata;
```

Maybe we need an intermediate structure to contain all the animation related stuff:
tmx_tile -> tmx_anim -> {tmx_frame, length, current_position, userdata, ...}

What do you think?

**Comment by reworks** [comment]
Yeah that sounds good. Looking at the TMX documentation ```<animation>``` is a part of ```<tile>``` so I don't think there is a need for the intermediate structure, from that perspective. I think its easier to have the union part of the ```_tmx_tile``` struct.

**Comment by baylej** [comment]
Do you see another node of the datastructure where that kind of `userdata` union would be helpful?
tmx_layer already has a `void *userdata;`, maybe we should replace it with the union?
