### ISSUE TITLE
SDL2 example, change <SDL2/SDL.h> to <SDL.h>

### ISSUE THREAD

**Issue by odrevet** [baylej/tmx#18]
The SDL include should be changed to "#include \<SDL.h>"
this is a common error, but really the sdl2-config utility include the SDL2 directory

sdl2-config --cflags
-I/usr/include/SDL2 -D_REENTRANT

**Comment by baylej** [comment]
Thank you for reporting this issue,
I'm not a SDL2 specialist, didn't know about the sdl2-config tool.
