### ISSUE TITLE
tmx_load fails if file contains empty object layer

### ISSUE THREAD

**Issue by howprice** [baylej/tmx#23]
To repro: Add a new object layer in Tiled, but leave it empty. Then try to load the saved .tmx file.

**Comment by baylej** [comment]
Problem identified:
When an object layer is empty, Tiled writes `<objectgroup name="Objects"/>` while the XML parser expects `<objectgroup name="Objects"></objectgroup>`.

A workaround is to use the latter by editing your TMX files manually.

A fix is being written, thanks for the report.
