### ISSUE TITLE
Colors as vectors

### ISSUE THREAD

**Issue by ForeverZer0** [baylej/tmx#41]
As the vast majority of users of this project will be using in conjunction with a graphics library such as OpenGL, perhaps instead of returning the color as an integer, return as a vec4 structure with four 32-bit floats. Conversion either way is trivial, but it would likely be more convenient to most users than an integer.

Another benefit would be eliminating any ambiguity of shifting bits and concern over the endianess of the machine to get the components.

**Comment by baylej** [comment]
The endianess of the machine is only an issue when reinterpreting the memory (eg: casting the integer to 4 bytes).

I've added two functions:
`tmx_col_to_bytes(uint32_t color);`
`tmx_col_to_floats(uint32_t color);`
See: https://libtmx.readthedocs.io/en/latest/functions.html#colour-conversion-functions
