### ISSUE TITLE
Segmentation fault rendering a layer

### ISSUE THREAD

**Issue by l33tllama** [baylej/tmx#45]
Hi,

I have used a built (release) version of tmx and imported it into my project. However it is failing to render a map. I have also tried compiling with the exact same sample code for allegro, same error. 

It seems that it's not loading the map tiles properly? I try to get the length of map->tiles and it's 1.

This could be some weird issue relating to my setup, but just wondering if someone has seen something similar and there may be a solution.

I'm building on Windows with both WSL and MinGW (MSYS2). Neither work. 

Thanks :)

Error:
`Thread 1 received signal SIGSEGV, Segmentation fault.
draw_layer (map=0x2c1e1e0, layer=0x2c20d10) at allegro.c:114
114                                             tileset = (ALLEGRO_BITMAP*)ts->image->resource_image;`

**Comment by baylej** [comment]
Hi, map->tiles is a C array, its length is in map->tilecount.
See: https://libtmx.readthedocs.io/en/latest/datastructure.html#c.tmx_map.tilecount

**Comment by baylej** [comment]
For the segfault, I'd need to reproduce it here to investigate, the allegro example should be able to load and display any map.

**Comment by l33tllama** [comment]
Hi, thanks for the quick reply! Here is a screenshot of contents of the map->tiles array https://i.imgur.com/xsG4sBf.png
Using the allegro example code.

**Comment by l33tllama** [comment]
Now, accessing the id of each tile in a loop,
`Thread 1 received signal SIGSEGV, Segmentation fault.
0x00401a92 in draw_layer (map=0x28fe130, layer=0x290f578) at allegro.c:102
102             printf("Tile GID at i=%d: %d\n", i, map->tiles[i]->id);`

:( Thanks for your help.

**Comment by l33tllama** [comment]
Here is a link to download my whole project folder for the allegro example. https://1drv.ms/u/s!AqiEsydnHmSdwb08CJPKYE9DFYxRtA?e=dDRBTU

Thanks again.

**Comment by baylej** [comment]
Map->tiles is a GID indexed array, also it's a sparse array, some GIDs have
no value (map->tiles[gid] may be null).

**Comment by l33tllama** [comment]
I've got it working. I used the source files from the tmx src directory. I imported them into my project, as well as MSYS2's libxml2 files. I'm compiling the tmx source files each time I compile my game however. With some minor changes it runs and displays my custom maps. But the standalone library is still giving issues, still not sure why.

**Comment by baylej** [comment]
Maybe you were using an older version that has a bug.
Glad you got it to work.
