### ISSUE TITLE
Documentation issue with SDL2 code

### ISSUE THREAD

**Issue by raysan5** [baylej/tmx#46]
Hey! Thanks for the raylib implementation and the great documentation.

Just noted an issue with [SDL2 Tile Layers Code](https://github.com/baylej/tmx/blob/master/doc/src/renderer-from-scratch.rst#tile-layers), it's Allegro code instead of SDL2.

Also, on the [Initial Setup code](https://github.com/baylej/tmx/blob/master/doc/src/renderer-from-scratch.rst#initial-set-up) for raylib you are including `<stdlib.h>` and `<string.h>`, those libraries are not required.

:)

**Comment by baylej** [comment]
Thanks, I'm bad at copying and pasting :upside_down_face:

Header `<stdlib.h>` is providing function declarations that are used later in the tutorial (malloc and free), but at that step it is indeed useless.
Header `<string.h>` will be removed.
