### ISSUE TITLE
Please add name property to object groups

### ISSUE THREAD

**Issue by bbswitchuser** [baylej/tmx#54]
The data structure for object_groups for libtmx can be found here: https://libtmx.readthedocs.io/en/latest/datastructure.html#c.tmx_object_group

There is no "name" field for the object group. The tmx format gives object groups names like most other types, however libtmx doesn't capture this. 

Reference: https://doc.mapeditor.org/en/stable/reference/tmx-map-format/#objectgroup

**Comment by baylej** [comment]
For layers of type objectgroup (L_OBJGR), their name attribute is in the tmx_layer node: 
https://libtmx.readthedocs.io/en/latest/datastructure.html#c.tmx_layer.name

**Comment by baylej** [comment]
This function may be helpful:
https://libtmx.readthedocs.io/en/latest/functions.html#c.tmx_find_layer_by_name
