### ISSUE TITLE
Load Buffer Base Path for images

### ISSUE THREAD

**Issue by RobLoach** [baylej/tmx#57]
When loading a map through a buffer, there is no base-path associated with where the file was loaded from. This means that if you load a map through a buffer, tmx will attempt to load images through `tmx_img_load_func(path)` without the basepath applied to where images actually exist.

```c
tmx_map* tmx_load_buffer(const char *buffer, int len);
```

For example...
```
resources/map/map.tmx
resources/map/tileset.png
```
If you load the map through a buffer, it will attempt to load `tileset.png` rather than `resources/map/tileset.png`.

**Comment by baylej** [comment]
Hi, the buffer/fd/callback set of load functions only exist for very specific cases, eg to load from a zipped file system, or using custom IO.
These are not the preferred way to load maps, why do you need to load from a buffer ?

**Comment by RobLoach** [comment]
Correct. This change will allow...
- Loading maps on systems that don't have File IO
- Compiling and embedding the map directly within the executable
- Loading maps from zipped archives, like you mentioned. Similar to how Quake 3 uses .pak files.

For my use case, I'm working on a [libretro](https://www.libretro.com/) core named [Lutro](https://lutro.libretro.com/) where games are distributed through a single `.lutro` file, which is similar to Love2D. A `.lutro` file is essentially a `.zip` file. Looking to add Tiled support directly into Lutro.
