### ISSUE TITLE
I can only build if i include stdlib.h into tmx_mem.c file  

### ISSUE THREAD

**Issue by Lucas-Marcel** [baylej/tmx#75]
F:\DEVELOPMENT_LIBRARIES\tmx-tmx_1.2.0\src\tmx_mem.c:11:1: note: 'realloc' is defined in header '<stdlib.h>'; did you forget to '#include <stdlib.h>'?
   10 | #include "tmx_utils.h"
  +++ |+#include <stdlib.h>

**Comment by popolony2k** [comment]
@Lucas-Marcel The same issue is happening when I'm trying to compile my project with TMX.
My project is using TMX for years and 2 weeks ago started crashing at compile time.
This started happening after I upgraded all macports installed libraries and at this moment libxml2 was upgraded from 2.11.6_0 to 2.12.5_0 
I think tmx_mem.c depends implicitly of what libxml2 is including and in the old version of libxml2 it was including stdlib.h in some point and in the newer version it is not referencing this include anymore.
Is an excellent idea keep TMX independent of libxml2 include by adding its dependencies directly as you made on your branch.
@baylej please consider accepting @Lucas-Marcel  pull request to the main branch.

Regards

**Comment by baylej** [comment]
Done 
Thank you for the in-depth analysis! :+1:

**Comment by popolony2k** [comment]
It is working again after your last merge on main.

Thanks
